package cn.xdl.ovls.study.video.dao;


import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Many;
import org.apache.ibatis.annotations.One;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.mapping.FetchType;
import org.apache.ibatis.type.JdbcType;

import cn.xdl.ovls.study.video.bean.Issue;

public interface IssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    @Delete({
        "delete from issue",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    @Insert({
        "insert into issue (headline, ",
        "issue_context, publish_time, ",
        "answer_count, browse_count, ",
        "video_id, user_id, ",
        "right_answer_id)",
        "values (#{headline,jdbcType=VARCHAR}, ",
        "#{issueContext,jdbcType=VARCHAR}, #{publishTime,jdbcType=TIMESTAMP}, ",
        "#{answerCount,jdbcType=INTEGER}, #{browseCount,jdbcType=INTEGER}, ",
        "#{videoId,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{rightAnswerId,jdbcType=INTEGER})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id",keyColumn="id")
    int insert(Issue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    @InsertProvider(type=IssueSqlProvider.class, method="insertSelective")
    int insertSelective(Issue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    @Select({
        "select",
        "id, headline, issue_context, publish_time, answer_count, browse_count, video_id, ",
        "user_id, right_answer_id",
        "from issue",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="headline", property="headline", jdbcType=JdbcType.VARCHAR),
        @Result(column="issue_context", property="issueContext", jdbcType=JdbcType.VARCHAR),
        @Result(column="publish_time", property="publishTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="answer_count", property="answerCount", jdbcType=JdbcType.INTEGER),
        @Result(column="browse_count", property="browseCount", jdbcType=JdbcType.INTEGER),
        @Result(column="video_id", property="videoId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="right_answer_id", property="rightAnswerId", jdbcType=JdbcType.INTEGER)
    })
    Issue selectByPrimaryKey(Integer id);
    
    
    
    /**
     * 查询某个视频中包含的问题的数量
     * */
    @Select({
        "select",
        "count(*)",
        "from issue",
        "where video_id = #{video_id,jdbcType=INTEGER}"
    })
    @Results()
    int selectCountByVideo(Integer video_id);
    
    
    /**
     * 根据视频ID查询该视频所有的问题，并按照发表时间降序排序
     * */
    @Select({
        "select",
        "id, headline, issue_context, publish_time, answer_count, browse_count, video_id, ",
        "user_id, right_answer_id",
        "from issue",
        "where video_id = #{video_id,jdbcType=INTEGER}",
        "order by publish_time desc"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="headline", property="headline", jdbcType=JdbcType.VARCHAR),
        @Result(column="issue_context", property="issueContext", jdbcType=JdbcType.VARCHAR),
        @Result(column="publish_time", property="publishTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="answer_count", property="answerCount", jdbcType=JdbcType.INTEGER),
        @Result(column="browse_count", property="browseCount", jdbcType=JdbcType.INTEGER),
        @Result(column="video_id", property="videoId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="right_answer_id", property="rightAnswerId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id",property="user",one=@One(fetchType=FetchType.EAGER,
        		select="cn.xdl.ovls.study.user.dao.UserMapper.selectByPrimaryKey")),
        @Result(column="id",property="answers",many=@Many(fetchType=FetchType.EAGER,
        		select="cn.xdl.ovls.study.video.dao.AnswerMapper.selectByIssue"))
    })
    List<Issue> selectByVideo(Integer video_id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    @UpdateProvider(type=IssueSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Issue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    @Update({
        "update issue",
        "set headline = #{headline,jdbcType=VARCHAR},",
          "issue_context = #{issueContext,jdbcType=VARCHAR},",
          "publish_time = #{publishTime,jdbcType=TIMESTAMP},",
          "answer_count = #{answerCount,jdbcType=INTEGER},",
          "browse_count = #{browseCount,jdbcType=INTEGER},",
          "video_id = #{videoId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "right_answer_id = #{rightAnswerId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Issue record);
}