package cn.xdl.ovls.study.user.bean;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

import cn.xdl.ovls.study.video.bean.Note;
import cn.xdl.ovls.study.video.bean.Video;

public class CollectNote implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_note.id
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_note.user_id
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_note.note_id
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    private Integer noteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_note.collect_time
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    private Date collectTime;
    
    /**
     * 收藏的笔记详细信息
     * */
    private Note note;
    
    /**
     * 笔记所在的视频信息
     * */
    private Video video;

    public Note getNote() {
		return note;
	}

	public void setNote(Note note) {
		this.note = note;
	}

	public Video getVideo() {
		return video;
	}

	public void setVideo(Video video) {
		this.video = video;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_note.id
     *
     * @return the value of collect_note.id
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_note.id
     *
     * @param id the value for collect_note.id
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_note.user_id
     *
     * @return the value of collect_note.user_id
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_note.user_id
     *
     * @param userId the value for collect_note.user_id
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_note.note_id
     *
     * @return the value of collect_note.note_id
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    public Integer getNoteId() {
        return noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_note.note_id
     *
     * @param noteId the value for collect_note.note_id
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    public void setNoteId(Integer noteId) {
        this.noteId = noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_note.collect_time
     *
     * @return the value of collect_note.collect_time
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8")
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_note.collect_time
     *
     * @param collectTime the value for collect_note.collect_time
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }
}