package cn.xdl.ovls.study.user.dao;


import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.xdl.ovls.study.user.bean.EvaluationLike;

public interface EvaluationLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation_like
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    @Delete({
        "delete from evaluation_like",
        "where Id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation_like
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    @Insert({
        "insert into evaluation_like (Id, evaluation_id, ",
        "user_id, like_time)",
        "values (#{id,jdbcType=INTEGER}, #{evaluationId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER}, #{likeTime,jdbcType=TIMESTAMP})"
    })
    int insert(EvaluationLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation_like
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    @InsertProvider(type=EvaluationLikeSqlProvider.class, method="insertSelective")
    int insertSelective(EvaluationLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation_like
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    @Select({
        "select",
        "Id, evaluation_id, user_id, like_time",
        "from evaluation_like",
        "where Id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="Id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="evaluation_id", property="evaluationId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="like_time", property="likeTime", jdbcType=JdbcType.TIMESTAMP)
    })
    EvaluationLike selectByPrimaryKey(Integer id);
    
    
    /**
     * 通过userId查询该User的所有点赞信息
     * */
    @Select({
        "select",
        "Id, evaluation_id, user_id, like_time",
        "from evaluation_like",
        "where user_id = #{user_id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="Id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="evaluation_id", property="evaluationId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="like_time", property="likeTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<EvaluationLike> selectByUser(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation_like
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    @UpdateProvider(type=EvaluationLikeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EvaluationLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation_like
     *
     * @mbggenerated Wed Oct 03 18:44:56 CST 2018
     */
    @Update({
        "update evaluation_like",
        "set evaluation_id = #{evaluationId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "like_time = #{likeTime,jdbcType=TIMESTAMP}",
        "where Id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(EvaluationLike record);
}